In [1]:
import numpy as np


In [2]:
arr = np.arange(24)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [4]:
reshaped = arr.reshape(4, 3, 2)

In [5]:
reshaped

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [6]:
transposed = reshaped.transpose(0, 2, 1)


In [7]:
transposed

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]],

       [[12, 14, 16],
        [13, 15, 17]],

       [[18, 20, 22],
        [19, 21, 23]]])

In [8]:
print("Final Shape:", transposed.shape)
print("Final Array:\n", transposed)

Final Shape: (4, 2, 3)
Final Array:
 [[[ 0  2  4]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9 11]]

 [[12 14 16]
  [13 15 17]]

 [[18 20 22]
  [19 21 23]]]
