In [1]:
import numpy as np

In [3]:
a = [1,2,3,4]  
b = [5,6,7,8]
a+b    ###[6,8,10,12]

[1, 2, 3, 4, 5, 6, 7, 8]

In [4]:
[a[i] + b[i] for i in range(len(a))]

[6, 8, 10, 12]

In [6]:
a = np.array([1,2,3,4])
b=  np.array([4,5,6,7])
a+b

array([ 5,  7,  9, 11])

In [13]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
arr[1:,::2 ]   ## start_row:end_row,start_col:end_column

array([[4, 6],
       [7, 9]])

In [32]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
np.eye(3,3).astype("int32").dtype

dtype('int32')

In [67]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [64]:
a = np.arange(10)

In [65]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [69]:
np.linspace(0,11,5)

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

In [70]:
### Vector operation with scaler values

In [95]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [82]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [107]:
a = [1,2,3,4,5,6,7,8,9]

In [119]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [112]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [110]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [113]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [114]:
np.linalg.det(a)

np.float64(-9.51619735392994e-16)

In [115]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [117]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [118]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [154]:
a = np.array([1,2,3,4,5,6,7,8,9,10,4,1])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  1])

In [151]:
np.resize(a,(4,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  4,  1],
       [ 2,  3,  4,  5]])

In [155]:
np.split(a,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10,  4,  1])]

Copy and Views

In [179]:
arr = np.array([1,2,3,4,5,6])

In [175]:
b = arr.view()

In [176]:
b[0] = 10

In [178]:
arr,b

(array([10,  2,  3,  4,  5,  6]), array([10,  2,  3,  4,  5,  6]))

In [180]:
c = arr.copy()

In [183]:
arr,c

(array([1, 2, 3, 4, 5, 6]), array([11,  2,  3,  4,  5,  6]))

In [182]:
c[0] = 11

In [185]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [186]:
np.sum(a,axis=0)

array([12, 15, 18])

In [187]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [189]:
def mean(array):
    n = len(array)
    return np.sum(array)/n

In [190]:
mean(np.array([1,2,3,4,5,6]))

np.float64(3.5)

In [195]:
def variance(array):
    n = len(array)
    m = mean(array)
    return np.sum((array - m)**2)/n

In [196]:
variance(np.array([1,2,3,4,5,6]))

np.float64(2.9166666666666665)

In [198]:
a = np.array([[1,2,3],
              [4,5,6]])

In [199]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [201]:
a.flatten()

array([1, 2, 3, 4, 5, 6])